--[[
    This script can auto load font which define in external ass file.

    When open a video, this script search for sub tracks with external flag in the track list;
    Then script parse sub file (must be a ass type sub file), get font name list.
    This script find real font file in font dir accounding font name,
    create a symbol link for font file under a temp dir.

    Finally, script use the path of the temp dir as the value of the property `sub-fonts-dir`,
    libass would load font in the temp dir.

    This script requires a font dir, this dir stores font files.
    The dir path must be passed to the `fontDir` script-opt.

    The font dir must contain a file called fc-subs.db, the file is generated by a project `FontLoaderSub`.
    In fact, the idea of writing this script came from this project

    FontLoaderSub: https://github.com/yzwduck/FontLoaderSub
]]
--

local utils = require "mp.utils"
local log = require "mp.msg"
local common = require "common"
local ass = require "ass"
local index = require "index"
local fontReport = require "report"

local options = {
    fontDir = "",
    cacheDir = "~~/fontCache/",
    remoteFontDir = "",
    report = false
}

local function scanNewSubFile(ctx, trackList)
    local subFileList = {}
    local size = 0
    for _, track in pairs(trackList) do
        if track.type == 'sub' and track.external and track.codec ~= 'null' then
            local path = track["external-filename"]
            if utils.file_info(path) == nil then
                log.error("sub file [" .. path .. "] not found")
                goto continue
            end
            if ctx.assFileSet[path] == nil then
                size = size + 1
                subFileList[size] = path
            end
        end
        ::continue::
    end
    return subFileList, size
end

local function loadFont(ctx, trackList)
    local subFileList, subFileSize = scanNewSubFile(ctx, trackList)
    local newFont = {}
    local newFontSize = 0

    -- detect video change and reset state
    local curVideo = mp.get_property("path") or ""
    if ctx.video ~= curVideo then
        ctx.fontSet = {}
        ctx.assFileSet = {}
        ctx.subFiles = {}
        ctx.video = curVideo
        if ctx.reportEnabled then
            fontReport.video(ctx.video, ctx.cacheKey, ctx.baseCacheDir)
        end
    end

    for i = 1, subFileSize do
        local file = subFileList[i]
        ctx.assFileSet[file] = false
        local fontList = ass.getFontListFromAss(file, ctx)
        fontList = fontList or {}

        local requiredFonts = {}
        local loadedFonts = {}
        local failedFonts = {}
        local seenFace = {}

        for _, face in pairs(fontList) do
            if seenFace[face] then goto continue_face end
            seenFace[face] = true
            table.insert(requiredFonts, face)
            local status = ctx.fontSet[face]
            if status == nil then
                local fontFromIdx = ctx.fontIndex[face]
                if fontFromIdx ~= nil then
                    newFont[fontFromIdx.filepath] = fontFromIdx.filename
                    newFontSize = newFontSize + 1
                    table.insert(loadedFonts, face .. " -> " .. fontFromIdx.filepath)
                    for _, face1 in pairs(fontFromIdx.faces) do
                        ctx.fontSet[face1] = true
                    end
                else
                    ctx.fontSet[face] = false
                    table.insert(failedFonts, face)
                    log.warn("font not find: " .. face)
                end
            elseif status == true then
                local fontFromIdx = ctx.fontIndex[face]
                table.insert(loadedFonts, face .. " -> " .. fontFromIdx.filepath)
            else
                table.insert(failedFonts, face)
            end
            ::continue_face::
        end

        ctx.subFiles[file] = {
            styleFontMap = (ctx.subFiles[file] and ctx.subFiles[file].styleFontMap) or nil,
            usedSet = (ctx.subFiles[file] and ctx.subFiles[file].usedSet) or nil,
            required = requiredFonts,
            loaded = loadedFonts,
            failed = failedFonts
        }
        if ctx.reportEnabled then
            fontReport.subtitle(ctx, file, ctx.cacheKey, ctx.baseCacheDir)
        end
    end

    for filepath, filename in pairs(newFont) do
        local linkFileName = filepath == filename and filename or filepath:gsub('/', '-')
        local linkFile = utils.join_path(ctx.fontCacheDir, linkFileName)
        local sourceFile = utils.join_path(ctx.fontDir, filepath)
        log.debug("create link file: " .. linkFile)
        log.info("load font: " .. filepath)
        common.link(sourceFile, linkFile)
        ctx.linkFileSize = ctx.linkFileSize + 1
        ctx.linkFileList[ctx.linkFileSize] = linkFile
    end

    if newFontSize > 0 then
        local sid = mp.get_property_number("sid") or -1
        if sid > 0 then
            mp.set_property_number("sid", 0)
            mp.set_property_number("sid", sid)
        end
    end
end

local function removeCache(ctx)
    for i = 1, ctx.linkFileSize do
        local linkFile = ctx.linkFileList[i]
        log.debug("remove font link file: " .. linkFile)
        local _, filename = utils.split_path(linkFile)
        log.info("unload font: " .. filename)
        common.unlink(linkFile)
    end
    log.debug("remove font cache dir: " .. ctx.fontCacheDir)
    common.rmdir(ctx.fontCacheDir)
end

local function main()
    require "mp.options".read_options(options, "font_loader")

    local baseCacheDir = mp.command_native({ "expand-path", options.cacheDir })
    log.info("create base cache dir: " .. baseCacheDir)
    common.mkdir(baseCacheDir)

    local fontIndex, fontDir = index.load(options)

    local cacheKey = os.date("%Y%m%d%H%M%S_") .. common.randomString(6)
    local fontCacheDir = utils.join_path(baseCacheDir, cacheKey)
    log.info("create font cache dir, path is: " .. fontCacheDir)
    common.mkdir(fontCacheDir)

    local context = {
        fontIndex = fontIndex,
        fontDir = fontDir,
        fontCacheDir = fontCacheDir,
        cacheKey = cacheKey,
        baseCacheDir = baseCacheDir,
        reportEnabled = options.report,
        assFileSet = {},
        fontSet = {},
        video = "",
        subFiles = {},
        linkFileList = {},
        linkFileSize = 0,
    }

    mp.set_property("sub-fonts-dir", fontCacheDir)
    mp.observe_property("track-list", "native", function(_, trackList)
        loadFont(context, trackList)
    end)
    mp.register_event("shutdown", function()
        removeCache(context)
    end)
end

main()
